# pdf_report.py
# 12-Jan-26: Added color coded "Quick Actions" section and Disclaimer Section
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib.colors import HexColor
from io import BytesIO
import json
from datetime import datetime
from zoneinfo import ZoneInfo


IST = ZoneInfo("Asia/Kolkata")


def hex_to_rgb(hex_color: str):
    """Convert hex color string to RGB tuple for ReportLab."""
    hex_color = hex_color.lstrip('#')
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def build_pdf(stock_name: str, raw_text: str, strategies_json: dict, quick_action: dict = None):
    """
    Creates a multi-page PDF report with Quick Action positioned below "Generated by...".
    stock_name: 'RELIANCE.NS'
    raw_text: LLM raw analysis
    strategies_json: final strategies dict
    quick_action: {"bias": "BUY", "color": "#0b7d3e", "message": "..."}
    """

    # Compute current IST timestamp at call time (not at import time)
    now_ist = datetime.now(IST)
    date_time_str = now_ist.strftime("%d-%b-%Y %I:%M%p")

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    normal = styles["Normal"]
    normal.leading = 16
    normal.alignment = TA_LEFT

    title_style = styles["Title"]
    subtitle_style = styles["Heading2"]
    header_style = styles["Heading3"]

    # Custom style for Quick Action bias label (bold, centered, white text)
    quick_action_label_style = ParagraphStyle(
        "QuickActionLabel",
        parent=styles["Normal"],
        fontSize=14,
        textColor=HexColor("#FFFFFF"),
        alignment=TA_CENTER,
        fontName="Helvetica-Bold"
    )

    # Custom style for Quick Action message (black text)
    quick_action_msg_style = ParagraphStyle(
        "QuickActionMessage",
        parent=styles["Normal"],
        fontSize=11,
        textColor=HexColor("#000000"),
        alignment=TA_LEFT,
        leading=14
    )

    # Custom style for disclaimer (smaller, grey text)
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=HexColor("#555555"),
        alignment=TA_LEFT,
        leading=12
    )

    flow = []
    stock_upper = (stock_name or "").upper()

    # ---------------------
    # COVER PAGE HEADER
    # ---------------------
    flow.append(Paragraph("Stock Analysis Report", title_style))
    flow.append(Paragraph(f"{date_time_str} IST - This analysis is for your selected stock: {stock_upper}", subtitle_style))
    flow.append(Spacer(1, 0.3 * inch))
    flow.append(Paragraph("Generated by: AI Deep Research Trading Analyst", normal))
    flow.append(Spacer(1, 0.3 * inch))

    # ---------------------
    # QUICK ACTION SECTION (below "Generated by...")
    # ---------------------
    if quick_action and quick_action.get("bias"):
        bias = quick_action.get("bias", "WAIT")
        color_hex = quick_action.get("color", "#fd7e14")  # use hex color from quick_action
        message = quick_action.get("message", "No action available.")

        # Convert hex to HexColor for ReportLab
        try:
            bg_color = HexColor(*hex_to_rgb(color_hex))
        except Exception:
            bg_color = HexColor("#fd7e14")  # fallback orange

        # Create a table with colored background for Quick Action
        quick_action_data = [
            [
                Paragraph(f"Quick Action – {bias}", quick_action_label_style),
                Paragraph(message, quick_action_msg_style)
            ]
        ]

        quick_action_table = Table(quick_action_data, colWidths=[1.8 * inch, 4.2 * inch])
        quick_action_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg_color),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("BORDER", (0, 0), (-1, -1), 1),
            ("BORDERCOLOR", (0, 0), (-1, -1), HexColor("#cccccc")),
        ]))

        flow.append(quick_action_table)
        flow.append(Spacer(1, 0.4 * inch))

    # ---------------------
    # RAW ANALYSIS SECTION
    # ---------------------
    flow.append(Paragraph("Trainer Analysis", header_style))
    flow.append(Spacer(1, 0.15 * inch))

    # Split by paragraph breaks
    paragraphs = raw_text.split("\n\n")
    for para in paragraphs:
        clean_para = para.replace("\n", " ").strip()
        if clean_para:
            flow.append(Paragraph(clean_para, normal))
            flow.append(Spacer(1, 0.15 * inch))

    # ---------------------
    # DISCLAIMER SECTION
    # ---------------------
    flow.append(Spacer(1, 0.3 * inch))
    flow.append(Paragraph("Disclaimer", header_style))
    flow.append(Spacer(1, 0.15 * inch))

    disclaimer_text = (
        "<b>•</b> This tool is for informational and educational purposes only. It is not investment, trading, tax, "
        "or legal advice. Always do your own research and consult a registered financial advisor before "
        "making any trading or investment decisions.<br/><br/>"
        "<b>•</b> Price data, OHLC candles, indicators, and signals shown in this application are derived from API "
        "sources and internal calculations. They may differ from values shown on broker terminals (such as "
        "Zerodha), ChartIQ, or other charting platforms due to data latency, different feeds, rounding "
        "methods, time-zone handling, and aggregation logic. These differences are expected for third-party tools.<br/><br/>"
        "<b>•</b> No guarantee is given that any data, indicator, signal, or analysis in this application is complete, "
        "accurate, or real-time. Past performance does not guarantee future results. Trading and investing in "
        "the markets involve substantial risk of loss. You are solely responsible for your own trading and "
        "investment decisions and for managing your risk."
    )

    flow.append(Paragraph(disclaimer_text, disclaimer_style))
    # At the very end, before doc.build()
    flow.append(Spacer(1, 0.5 * inch))
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#999999"),
        alignment=TA_CENTER
    )
    flow.append(Paragraph(f"Generated by AI Deep Research Trading Analyst • {date_time_str}", footer_style))

    doc.build(flow)
    buffer.seek(0)
    return buffer